### ISSUE TITLE
Default configuration prevents Nova KVM hypervisors from working

### ISSUE THREAD

**Issue by diurnalist** [ChameleonCloud/chi-in-a-box#100]
We have some values in defaults.yml that need to be undone if you want to use this to deploy a KVM cloud.

```yaml
nova_compute_virt_type: none
# We are not using any VNC consoles; the serialproxy is not considered a 'nova_console'
nova_console: none
```

These values are set to "none" to turn off some aspects of the deploy specific to a bare metal-only cloud, and should be customizable if a KVM deployment is desired.

For example, a KVM deployment may want:

```yaml
nova_compute_virt_type: kvm
nova_console: novnc
```
