### ISSUE TITLE
Post-Deploy Error

### ISSUE THREAD

**Issue by tislam93** [ChameleonCloud/chi-in-a-box#103]
We are deploying bare-metal chi-in-a-box on our internal deployment. I got an error (attached as image) regarding the public network while running the post-deploy (mentioned in quick start guide). I do have mentioned my "public" network along with the external interface (as mentioned on step 5 of the site specific configuration). 
Our CHI setup is working and I can login to the dashboard. All steps have been successful till the deploy step. However, I am stuck at the post-deploy step and could not figure out what's missing. I need guidance on resolving the issue (if it is a known one) or a pointer to relevant configuration checks if I am missing something. Thank you!

![Post-deploy Error](https://user-images.githubusercontent.com/80611333/120864201-7459d800-c551-11eb-8e50-299cb6d0ddde.PNG)

**Comment by diurnalist** [comment]
Hi @taimoorulislam93, can you please post the value of your `neutron_networks:` in your site-config's globals.yml? Could be there's a bug.

**Comment by tislam93** [comment]
Our Neutron configuration in the globals.yml file is posted below. The network mentioned in the cidr is our campus network and we are treating it as public in our setup. This IP block is NATed to internet by our campus network. 
eno2 has IP address 10.24.85.127 and it is reachable to internet. 

```
neutron_networks:
   - name: physnet1
     on_demand_vlan_ranges:
       - 200:250
     reservable_vlan_ranges:
       - 250:300
     bridge_name: br-em1
     external_interface: enp6s0f0
   - name: public
     bridge_name: br-ex
     external_interface: eno2
     cidr: 10.24.84.0/22
```
