### ISSUE TITLE
k3s playbook not working

### ISSUE THREAD

**Issue by samiemostafavi** [ChameleonCloud/chi-in-a-box#225]
Hi,

I am trying to run chi-in-a-box on Ubuntu server 20.0.4.
I have only one controller node and I run `cc-ansible` locally. I use the following `site-config/default.yml` file (on the first round):

```
openstack_region_name: CHI@ExPECA
chameleon_site_name: expeca
kolla_internal_vip_address: "10.20.111.254"
kolla_external_vip_address: "10.0.87.254"
neutron_networks:
- name: public
  bridge_name: br-ex
  external_interface: veth-publicb
  cidr: 10.0.87.0/24
  gateway_ip: 10.0.87.1
  allocation_pools:
    - start: 10.0.87.20
      end: 10.0.87.250
- name: physnet1
  bridge_name: br-internal
  external_interface: veth-privateb
  on_demand_vlan_ranges:
    - 200:250
  reservable_vlan_ranges:
    - 251:300
ironic_provisioning_network_vlan: 200
ironic_provisioning_network_cidr: 10.51.0.0/24
enable_k3s: no
enable_zun: yes
```

As you mention in `Edge v2 implementation` PR, I have to:

1. Run a full deploy with enable_k3s set to false.
2. Set enable_k3s to true.
3. Run cc-ansible --playbook ./playbooks/k3s.yaml
4. Run cc-ansible deploy again.

In the first step I get an error:
```
TASK [zun : Copying over kubeconfig for k8s agent] 
No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found
```
Since it is the first round, I make ansible ignore this error and I continue (by explicitly mentioning `ignore_errors: yes` for this task).  

Then I set `enable_k3s: yes` in the `site-config/default.yml` and run `cc-ansible --playbook ./playbooks/k3s.yaml`. 
I get an error indicating that Kubernetes is not installed.

```
TASK [k3s : Apply Calico operator]
Failed to import the required Python library (kubernetes) on client's Python /etc/ansible/venv/bin/python
```

Is there any thing that I am missing?

Best,
Samie
