### ISSUE TITLE
MariaDB access denied for root

### ISSUE THREAD

**Issue by samiemostafavi** [ChameleonCloud/chi-in-a-box#231]
Hi,

I am using Ubuntu 20.04.5 and trying to install chi-in-a-box in our lab.
Even when I start `cc-ansible deploy` from a clean slate, during the configuration of mariadb role, there is a persistent error showing up regarding registering the root user.

```
TASK [mariadb : Creating shard root mysql user] ************************************************************************************************************************************************************
fatal: [edge]: FAILED! => {"action": "mysql_user", "changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /var/lib/ansible/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'controller' (using password: YES)\")"}
``` 

I suggest solving this issue using docker to enable root user access instead of Ansible `mysql_user` module. I could pull it off by replacing `Creating shard root mysql user` task in the file `roles/mariadb/tasks/register.yml` with the following:

```
- name: Creating shard root mysql user
  become: true
  command: >
    docker exec {{ mariadb_service.container_name }}
    mysql -u{{ database_user }} -p{{ database_password }} -e "GRANT ALL PRIVILEGES ON *.* TO '{{ database_user }}'@'%' IDENTIFIED BY '{{ database_password }}';"
  when: mariadb_shard_id == mariadb_default_database_shard_id
  notify:
    - restart mariadb
```

I hope you find it useful.

Best,
Samie
